import fdb
import os

# Caminho da pasta atual
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
print("BASE_DIR =", BASE_DIR)

# Caminho absoluto do banco
DB_PATH = os.path.abspath(os.path.join(BASE_DIR, "..", "database", "atividades.fdb")).replace("/", "\\")
print("DB_PATH =", DB_PATH)

# Carrega a DLL do Firebird Embedded
fbclient_path = os.path.abspath(os.path.join(BASE_DIR, "..", "libs", "fbclient.dll"))
fdb.load_api(fbclient_path)

#Configs Banco
DB_USER = 'sysdba'
DB_PASSWORD = 'admin123'

def criar_banco_se_nao_existir():
    if not os.path.exists(DB_PATH):
        print("Criando banco de dados...")
        fdb.create_database(
            dsn=DB_PATH,
            user=DB_USER,
            password=DB_PASSWORD,
            page_size=4096,
            charset='UTF8'
        )

def conectar():
    criar_banco_se_nao_existir()
    con = fdb.connect(
        dsn=DB_PATH,
        user=DB_USER,
        password=DB_PASSWORD,
        charset='UTF8'
    )
    criar_tabela_se_nao_existir(con)
    return con
    
def criar_tabela_se_nao_existir(con):
    cur = con.cursor()
    cur.execute("""
        SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME='ATIVIDADES'
    """) 
    if not cur.fetchone():
        print("Criando tabela ATIVIDADES...")
        cur.execute("""
            CREATE TABLE atividades (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nome VARCHAR(100),
                atividade VARCHAR(255)
            )
        """)   
        con.commit()

